title: Your Site Name
description: A minimal theme with a bold header and easy-to-read content sections.
url: "https://yourusername.github.io"
baseurl: ""

# Remote theme
remote_theme: pages-themes/hacker@v0.2.0

# Author info
author:
  name: Your Name
  email: your-email@example.com

# Social links (optional)
social:
  github: https://github.com/yourusername
  linkedin: https://www.linkedin.com/in/yourprofile

# Plugins
markdown: kramdown
plugins:
  - jekyll-feed
